import { el, $, announce } from '../utils/dom.js';
import { routes, routeForPath, withBase } from '../config/routes.js';
import { environment } from '../config/environment.js';
import { getPreferences, savePreferences } from '../utils/preferences.js';

const items = [
  ['Qué es OLLIN', '#que-es-ollin', '¿Qué es OLLIN?'], ['Ecosistema', '#ecosistema', 'Ecosistema'], ['Proyectos', routes.proyectos, 'Proyectos'], ['Principios', routes.principios, 'Principios'], ['Yancuic', routes.tlatolli, 'Yancuic'], ['Sobre OLLIN', routes.sobre, 'Sobre OLLIN']
];
function asset(path) { return withBase(`/${path}`); }
function navHref(href) { return routeForPath() === 'home' ? href : (href.startsWith('#') ? withBase(href) : href); }

const icon = (d) => `<svg viewBox="0 0 24 24" aria-hidden="true">${d}</svg>`;
const tabs = [
  ['Inicio', 'home', icon('<path d="M3 11l9-7 9 7v9a1 1 0 0 1-1 1h-5v-6H9v6H4a1 1 0 0 1-1-1z"/>'), routes.home],
  ['Ecosistema', 'ecosistema', icon('<circle cx="12" cy="12" r="3"/><circle cx="12" cy="4" r="1.6"/><circle cx="20" cy="15" r="1.6"/><circle cx="4" cy="15" r="1.6"/><path d="M12 6v3M18.6 14l-3.3-1.5M5.4 14l3.3-1.5"/>'), '#ecosistema'],
  ['Proyectos', 'proyectos', icon('<rect x="3" y="3" width="8" height="8" rx="2"/><rect x="13" y="3" width="8" height="8" rx="2"/><rect x="3" y="13" width="8" height="8" rx="2"/><rect x="13" y="13" width="8" height="8" rx="2"/>'), routes.proyectos],
  ['Yancuic', 'tlatolli', icon('<path d="M4 5h16v11H9l-5 4z"/><path d="M8 9h8M8 12h5"/>'), routes.tlatolli],
];
function tabbar(current) {
  const bar = el('nav', { className: 'app-tabbar', attrs: { 'aria-label': 'Navegación de aplicación' } }, [...tabs.map(([label, key, svg, href]) => el('a', { href: key === 'ecosistema' ? navHref(href) : href, innerHTML: `${svg}<span>${label}</span>`, attrs: current === key ? { 'aria-current': 'page' } : {} })), el('button', { id: 'more-toggle', type: 'button', innerHTML: `${icon('<circle cx="5" cy="12" r="1.5"/><circle cx="12" cy="12" r="1.5"/><circle cx="19" cy="12" r="1.5"/>')}<span>Más</span>`, attrs: { 'aria-expanded': 'false', 'aria-controls': 'more-sheet' } })]);
  bar.addEventListener('click', (event) => { const link = event.target.closest('a'); if (!link) return; bar.querySelectorAll('a').forEach((a) => a.removeAttribute('aria-current')); link.setAttribute('aria-current', 'page'); });
  return bar;
}
function moreSheet(routeKey) {
  const sheet = el('div', { className: 'more-sheet', id: 'more-sheet', attrs: { hidden: '' } }, [...[['Principios', routes.principios], ['Tecnología', routes.tecnologia], ['Impacto', routes.impacto], ['Sobre OLLIN', routes.sobre], ['Participa', routeKey === 'home' ? '#participa' : routes.contacto]].map(([text, href]) => el('a', { href, text })), el('button', { type: 'button', text: '◐ Cambiar tema', onclick: () => $('#theme-toggle')?.click() })]);
  const toggle = (open) => { sheet.hidden = !open; $('#more-toggle')?.setAttribute('aria-expanded', String(open)); };
  document.addEventListener('click', (event) => { const more = event.target.closest('#more-toggle'); if (more) toggle(sheet.hidden); else if (!sheet.contains(event.target) || event.target.closest('a')) toggle(false); });
  document.addEventListener('keydown', (event) => { if (event.key === 'Escape') toggle(false); });
  return sheet;
}

export function renderShell(routeKey) {
  const current = routeKey || routeForPath();
  const header = el('header', { className: `site-header${current === 'home' ? ' site-header--hero' : ''}` }, [el('div', { className: 'container header-inner' }, [el('a', { className: 'brand', href: routes.home, attrs: { 'aria-label': 'OLLIN, inicio' } }, [el('img', { className: 'light-logo', src: asset('src/assets/brand/logo.svg'), alt: 'OLLIN' }), el('img', { className: 'dark-logo', src: asset('src/assets/brand/logoinvertido.svg'), alt: '' })]), el('nav', { className: 'main-nav', attrs: { 'aria-label': 'Navegación principal' } }, items.map(([label, href, key]) => el('a', { href: navHref(href), text: label, attrs: current === key ? { 'aria-current': 'page' } : {} }))), el('div', { className: 'header-actions' }, [el('button', { className: 'theme-button', id: 'theme-toggle', type: 'button', text: '◐', attrs: { 'aria-label': 'Cambiar tema' } }), el('a', { className: 'button', href: routeKey === 'home' ? '#participa' : routes.contacto, text: 'Participa' }), el('button', { className: 'menu-button', id: 'menu-toggle', type: 'button', text: '☰', attrs: { 'aria-label': 'Abrir menú', 'aria-expanded': 'false', 'aria-controls': 'mobile-drawer' } })])]), el('div', { className: 'mobile-drawer', id: 'mobile-drawer', attrs: { hidden: '' } }, [el('nav', { attrs: { 'aria-label': 'Navegación móvil' } }, items.map(([label, href]) => el('a', { href: navHref(href), text: label }))), el('a', { className: 'button', href: routeKey === 'home' ? '#participa' : routes.contacto, text: 'Participa' })])]);
  document.body.prepend(el('a', { className: 'skip-link', href: '#contenido-principal', text: 'Saltar al contenido' })); document.body.prepend(header); document.body.append(tabbar(current), moreSheet(routeKey)); document.body.append(el('div', { id: 'site-live', className: 'sr-only', attrs: { 'aria-live': 'polite', 'aria-atomic': 'true' } })); setupShell();
}
function setupShell() { const root = document.documentElement; root.dataset.theme = getPreferences().theme || 'system'; const toggle = $('#theme-toggle'); toggle?.addEventListener('click', () => { const next = root.dataset.theme === 'dark' ? 'light' : root.dataset.theme === 'light' ? 'system' : 'dark'; root.dataset.theme = next; savePreferences({ theme: next }); announce(`Tema ${next === 'system' ? 'del sistema' : next} activado`); }); const menu = $('#menu-toggle'); const drawer = $('#mobile-drawer'); menu?.addEventListener('click', () => { const open = !drawer.hidden; drawer.hidden = open; drawer.classList.toggle('open', !open); menu.setAttribute('aria-expanded', String(!open)); menu.setAttribute('aria-label', open ? 'Abrir menú' : 'Cerrar menú'); if (!open) drawer.querySelector('a')?.focus(); }); drawer?.addEventListener('click', (event) => { if (event.target.matches('a')) { drawer.hidden = true; drawer.classList.remove('open'); menu?.setAttribute('aria-expanded', 'false'); } }); }
export function renderFooter() { const homeAnchor = (anchor) => routeForPath() === 'home' ? anchor : withBase(anchor); document.body.append(el('footer', { className: 'site-footer' }, [el('div', { className: 'container' }, [el('div', { className: 'footer-grid' }, [el('div', { className: 'prose' }, [el('a', { className: 'brand', href: routes.home }, [el('img', { className: 'light-logo', src: asset('src/assets/brand/logo.svg'), alt: 'OLLIN' }), el('img', { className: 'dark-logo', src: asset('src/assets/brand/logoinvertido.svg'), alt: '' })]), el('p', { text: 'Movimiento que conecta.' }), el('p', { className: 'muted', text: 'Infraestructura digital mexicana para conectar aplicaciones, personas, cultura, conocimiento, oportunidades y servicios.' })]), el('nav', { attrs: { 'aria-label': 'Explora' } }, [el('strong', { text: 'Explora' }), el('a', { href: homeAnchor('#que-es-ollin'), text: 'Qué es OLLIN' }), el('a', { href: homeAnchor('#ecosistema'), text: 'Ecosistema' }), el('a', { href: routes.proyectos, text: 'Proyectos' }), el('a', { href: routes.principios, text: 'Principios' })]), el('nav', { attrs: { 'aria-label': 'Conoce' } }, [el('strong', { text: 'Conoce' }), el('a', { href: routes.tecnologia, text: 'Tecnología' }), el('a', { href: routes.impacto, text: 'Impacto' }), el('a', { href: routes.tlatolli, text: 'Yancuic' }), el('a', { href: routes.sobre, text: 'Sobre OLLIN' })]), el('nav', { attrs: { 'aria-label': 'Participa' } }, [el('strong', { text: 'Participa' }), el('a', { href: routes.contacto, text: 'Contacto' }), el('a', { href: routes.instituciones, text: 'Instituciones' }), el('a', { href: routes.comunidades, text: 'Creadores y comunidades' }), el('a', { href: routes.talento, text: 'Talento' })])]), el('div', { className: 'footer-bottom' }, [el('span', { text: `© ${new Date().getFullYear()} OLLIN · Staging estático` }), el('a', { href: homeAnchor('#contenido-principal'), text: 'Volver arriba ↑' })])]) ])); }
