import { el, $, announce } from '../utils/dom.js';
import { routes, routeForPath, withBase } from '../config/routes.js';
import { environment } from '../config/environment.js';
import { getPreferences, savePreferences } from '../utils/preferences.js';

const items = [
  ['Qué es OLLIN', '#que-es-ollin', '¿Qué es OLLIN?'], ['Ecosistema', '#ecosistema', 'Ecosistema'], ['Proyectos', routes.proyectos, 'Proyectos'], ['Principios', routes.principios, 'Principios'], ['Tlatolli', routes.tlatolli, 'Tlatolli'], ['Sobre OLLIN', routes.sobre, 'Sobre OLLIN']
];
function asset(path) { return withBase(`/${path}`); }
function navHref(href) { return routeForPath() === 'home' ? href : (href.startsWith('#') ? withBase(href) : href); }

export function renderShell(routeKey) {
  const current = routeKey || routeForPath();
  const header = el('header', { className: 'site-header' }, [el('div', { className: 'container header-inner' }, [el('a', { className: 'brand', href: routes.home, attrs: { 'aria-label': 'OLLIN, inicio' } }, [el('img', { className: 'light-logo', src: asset('src/assets/brand/logo.svg'), alt: 'OLLIN' }), el('img', { className: 'dark-logo', src: asset('src/assets/brand/logoinvertido.svg'), alt: '' })]), el('nav', { className: 'main-nav', attrs: { 'aria-label': 'Navegación principal' } }, items.map(([label, href, key]) => el('a', { href: navHref(href), text: label, attrs: current === key ? { 'aria-current': 'page' } : {} }))), el('div', { className: 'header-actions' }, [el('button', { className: 'theme-button', id: 'theme-toggle', type: 'button', text: '◐', attrs: { 'aria-label': 'Cambiar tema' } }), el('a', { className: 'button', href: routeKey === 'home' ? '#participa' : routes.contacto, text: 'Participa' }), el('button', { className: 'menu-button', id: 'menu-toggle', type: 'button', text: '☰', attrs: { 'aria-label': 'Abrir menú', 'aria-expanded': 'false', 'aria-controls': 'mobile-drawer' } })])]), el('div', { className: 'mobile-drawer', id: 'mobile-drawer', attrs: { hidden: '' } }, [el('nav', { attrs: { 'aria-label': 'Navegación móvil' } }, items.map(([label, href]) => el('a', { href: navHref(href), text: label }))), el('a', { className: 'button', href: routeKey === 'home' ? '#participa' : routes.contacto, text: 'Participa' })])]);
  document.body.prepend(el('a', { className: 'skip-link', href: '#contenido-principal', text: 'Saltar al contenido' })); document.body.prepend(header); document.body.append(el('div', { id: 'site-live', className: 'sr-only', attrs: { 'aria-live': 'polite', 'aria-atomic': 'true' } })); setupShell();
}
function setupShell() { const root = document.documentElement; root.dataset.theme = getPreferences().theme || 'system'; const toggle = $('#theme-toggle'); toggle?.addEventListener('click', () => { const next = root.dataset.theme === 'dark' ? 'light' : root.dataset.theme === 'light' ? 'system' : 'dark'; root.dataset.theme = next; savePreferences({ theme: next }); announce(`Tema ${next === 'system' ? 'del sistema' : next} activado`); }); const menu = $('#menu-toggle'); const drawer = $('#mobile-drawer'); menu?.addEventListener('click', () => { const open = !drawer.hidden; drawer.hidden = open; drawer.classList.toggle('open', !open); menu.setAttribute('aria-expanded', String(!open)); menu.setAttribute('aria-label', open ? 'Abrir menú' : 'Cerrar menú'); if (!open) drawer.querySelector('a')?.focus(); }); drawer?.addEventListener('click', (event) => { if (event.target.matches('a')) { drawer.hidden = true; drawer.classList.remove('open'); menu?.setAttribute('aria-expanded', 'false'); } }); }
export function renderFooter() { const homeAnchor = (anchor) => routeForPath() === 'home' ? anchor : withBase(anchor); document.body.append(el('footer', { className: 'site-footer' }, [el('div', { className: 'container' }, [el('div', { className: 'footer-grid' }, [el('div', { className: 'prose' }, [el('a', { className: 'brand', href: routes.home }, [el('img', { className: 'light-logo', src: asset('src/assets/brand/logo.svg'), alt: 'OLLIN' }), el('img', { className: 'dark-logo', src: asset('src/assets/brand/logoinvertido.svg'), alt: '' })]), el('p', { text: 'Movimiento que conecta.' }), el('p', { className: 'muted', text: 'Infraestructura digital mexicana para conectar aplicaciones, personas, cultura, conocimiento, oportunidades y servicios.' })]), el('nav', { attrs: { 'aria-label': 'Explora' } }, [el('strong', { text: 'Explora' }), el('a', { href: homeAnchor('#que-es-ollin'), text: 'Qué es OLLIN' }), el('a', { href: homeAnchor('#ecosistema'), text: 'Ecosistema' }), el('a', { href: routes.proyectos, text: 'Proyectos' }), el('a', { href: routes.principios, text: 'Principios' })]), el('nav', { attrs: { 'aria-label': 'Conoce' } }, [el('strong', { text: 'Conoce' }), el('a', { href: routes.tecnologia, text: 'Tecnología' }), el('a', { href: routes.impacto, text: 'Impacto' }), el('a', { href: routes.tlatolli, text: 'Tlatolli' }), el('a', { href: routes.sobre, text: 'Sobre OLLIN' })]), el('nav', { attrs: { 'aria-label': 'Participa' } }, [el('strong', { text: 'Participa' }), el('a', { href: routes.contacto, text: 'Contacto' }), el('a', { href: routes.instituciones, text: 'Instituciones' }), el('a', { href: routes.comunidades, text: 'Creadores y comunidades' }), el('a', { href: routes.talento, text: 'Talento' })])]), el('div', { className: 'footer-bottom' }, [el('span', { text: `© ${new Date().getFullYear()} OLLIN · Staging estático` }), el('a', { href: homeAnchor('#contenido-principal'), text: 'Volver arriba ↑' })])]) ])); }
