import { el, $, announce } from './utils/dom.js';
import { routes, routeForPath } from './config/routes.js';
import { getProjects, getPrinciples, getCapabilities, getImpact, getArticles } from './services/content.service.js';
import { getContactChannel } from './services/external-channel.service.js';
import { renderShell, renderFooter } from './components/shell.js';
import { createCodexLoop } from './components/codex-loop.js';
import { createEcosystemDiagram } from './components/ecosystem-diagram.js';

const stylesheet = document.createElement('link');
stylesheet.rel = 'stylesheet';
stylesheet.href = `${new URL('./styles/app.css', import.meta.url).href}?v=20260920-safari`;
document.head.append(stylesheet);
import { projectCard, principleCard, impactCard, articleCard } from './components/cards.js';

const projects = getProjects();
const principles = getPrinciples();
const capabilities = getCapabilities();
const impact = getImpact();
const articles = getArticles();
const portadaAsset = `${new URL('./assets/brand/portada.png', import.meta.url).href}?v=20260918-hero`;
const codexAsset = `${new URL('./assets/brand/codices-en-movimiento.png', import.meta.url).href}?v=20260918-codices`;

function section(className = '', children = [], id = '') { return el('section', { className: `section ${className}`, id }, [el('div', { className: 'container' }, children)]); }
function heading(eyebrow, title, description) { return el('div', { className: 'section-heading' }, [el('span', { className: 'eyebrow', text: eyebrow }), el('h2', { text: title }), description ? el('p', { text: description }) : null]); }
function button(label, href, secondary = false) { return el('a', { className: `button${secondary ? ' secondary' : ''}`, href, text: label }); }
function notice(text) { return el('p', { className: 'notice', text }); }
function frame(eyebrow, title, description, content) { const main = el('main', { id: 'contenido-principal' }, [el('section', { className: 'page-hero' }, [el('div', { className: 'container page-hero-inner' }, [el('span', { className: 'eyebrow', text: eyebrow }), el('h1', { text: title }), el('p', { text: description })])]), ...content]); $('#app').replaceWith(main); return main; }

function renderHome() {
  const hero = el('section', { className: 'hero hero--cover', id: 'inicio' }, [el('div', { className: 'hero-media', attrs: { 'aria-hidden': 'true' } }, [el('img', { src: portadaAsset, alt: '', loading: 'eager', decoding: 'async' })]), el('div', { className: 'container hero-content' }, [el('div', { className: 'hero-utility' }, [el('span', { text: 'OLLIN / INICIO' }), el('span', { text: 'México · movimiento continuo' })]), el('div', { className: 'hero-grid' }, [el('div', { className: 'hero-copy glass-panel' }, [el('span', { className: 'eyebrow eyebrow-light', text: 'Infraestructura digital mexicana' }), el('h1', { text: 'Movimiento que conecta.' }), el('p', { className: 'lead', text: 'OLLIN crea la base para conectar aplicaciones, personas, cultura, conocimiento, oportunidades y servicios con tecnología humanista.' }), el('div', { className: 'hero-actions' }, [button('Conoce OLLIN', '#que-es-ollin'), button('Explora el ecosistema', '#ecosistema', true)]), el('a', { className: 'button ghost', href: '#codices', text: 'Recorre los códices ↓' })]), el('aside', { className: 'hero-side glass-panel' }, [el('span', { className: 'eyebrow eyebrow-light', text: 'Una visión compartida' }), el('p', { className: 'hero-side-title', text: 'Personas. Cultura. Ideas.' }), el('p', { className: 'hero-side-copy', text: 'Un ecosistema donde cada proyecto conserva su identidad y puede formar parte de algo mayor.' }), el('a', { className: 'hero-side-link', href: '#participa', text: 'Súmate al movimiento →' })])]), el('a', { className: 'hero-scroll', href: '#codices', text: 'Desplázate para explorar' })])]);
  const codices = createCodexLoop(codexAsset);
  const what = section('soft anchor-target', [heading('Qué es OLLIN', 'No construimos una sola aplicación. Construimos el ecosistema que permite que muchas existan y se conecten.', 'OLLIN es una infraestructura digital mexicana para crear y articular aplicaciones, comunidades y servicios con una visión compartida. Cada proyecto puede responder a una necesidad distinta y conservar su identidad, mientras aprovecha principios, estándares y capacidades comunes.'), el('p', { className: 'notice', text: 'Tecnología con propósito, diseñada desde México para fortalecer personas y comunidades.' }), el('div', { className: 'contrast-cards' }, [el('article', { className: 'contrast-card no' }, [el('span', { className: 'eyebrow', text: 'No somos' }), el('p', { text: 'Una app única, una colección de productos sin relación ni un portal que promete más de lo que existe.' })]), el('article', { className: 'contrast-card yes' }, [el('span', { className: 'eyebrow', text: 'Sí somos' }), el('p', { text: 'Una base común para proyectos conectados, con identidad propia y principios compartidos.' })])])], 'que-es-ollin');
  const ecosystem = section('anchor-target', [heading('Ecosistema', 'Una base compartida. Muchas experiencias posibles.', 'OLLIN organiza el ecosistema en tres niveles públicos y comprensibles. Esta vista explica relaciones, no componentes internos.'), createEcosystemDiagram(), el('p', { className: 'muted', style: 'margin-top:1rem', text: 'Cada proyecto puede crecer a su ritmo y conservar su voz, mientras se conecta con un marco común.' })], 'ecosistema');
  const projectSection = section('soft anchor-target', [heading('Proyectos', 'El movimiento toma distintas formas.', 'Cada iniciativa parte de una necesidad concreta y se integra al ecosistema OLLIN desde su propia identidad.'), el('div', { className: 'grid grid-3', id: 'proyectos' }, projects.slice(0, 3).map(projectCard)), notice('Los estados comunican el avance público de cada proyecto y deben actualizarse únicamente con información confirmada.'), el('a', { className: 'button secondary', href: routes.proyectos, text: 'Ver proyectos →' })], 'proyectos-seccion');
  const principleSection = section('anchor-target', [heading('Principios', 'La tecnología también expresa valores.', 'Estos principios orientan lo que OLLIN diseña, cómo lo comunica y la forma en que busca relacionarse con las personas.'), el('div', { className: 'grid grid-3', id: 'principios' }, principles.map(principleCard)), el('a', { className: 'button secondary', href: routes.principios, text: 'Lee nuestros principios →' })], 'principios-seccion');
  const technologySection = section('dark anchor-target', [heading('Tecnología', 'Infraestructura para conectar sin perder identidad.', 'OLLIN se diseña como una base modular y evolutiva. Hablamos públicamente de capacidades y principios; los detalles de implementación, seguridad y operación permanecen en documentación controlada.'), el('div', { className: 'tech-grid' }, capabilities.map((item) => el('article', { className: 'tech-card' }, [el('h3', { text: item.title }), el('p', { text: item.description })]))), notice('Esta descripción es conceptual y no revela arquitectura, algoritmos ni controles internos.'), button('Conoce nuestro enfoque tecnológico', routes.tecnologia, true)], 'tecnologia-seccion');
  const impactSection = section('soft anchor-target', [heading('Impacto', 'Tecnología que mueve capacidades, no solo pantallas.', 'OLLIN orienta su trabajo hacia cuatro dimensiones de impacto. Son compromisos y objetivos de diseño; las métricas se publicarán cuando existan datos verificables.'), el('div', { className: 'grid grid-4' }, impact.map(impactCard)), el('p', { className: 'notice', style: 'margin-top:1.2rem', text: 'OLLIN estudia modelos donde parte del valor generado por el ecosistema pueda retornar a las comunidades que lo hacen posible. Cualquier mecanismo se comunicará solo cuando cuente con definición jurídica, operativa y de gobernanza.' }), button('Conoce el impacto que buscamos', routes.impacto, true)], 'impacto-seccion');
  const tlatolliSection = section('anchor-target', [heading('Tlatolli', 'Ideas que ponen la tecnología en conversación.', 'Tlatolli será el espacio editorial de OLLIN para compartir avances, preguntas y aprendizajes sobre tecnología, cultura, comunidades, soberanía digital e investigación.'), el('div', { className: 'grid grid-3' }, articles.map(articleCard)), button('Ir a Tlatolli', routes.tlatolli, true)], 'tlatolli');
  const aboutSection = section('soft anchor-target', [heading('Sobre OLLIN', 'Ollin significa movimiento.', 'El nombre retoma el concepto náhuatl ollin, asociado con el movimiento y la transformación. Para nosotros, ese movimiento conecta personas, información, cultura, conocimiento, oportunidades y comunidades.'), el('div', { className: 'prose' }, [el('p', { text: 'OLLIN nace de una convicción: México puede construir tecnología con identidad propia, rigor y propósito humano. Proyectos como Cuicoyan convierten esa visión en experiencias concretas y abren el camino para un ecosistema mayor.' }), el('p', { className: 'notice', text: 'No buscamos poner una identidad cultural sobre la tecnología. Buscamos que la tecnología nazca del contexto, dialogue con él y contribuya a moverlo.' })]), button('Conoce nuestra historia', routes.sobre, true)], 'sobre-ollin');
  const participate = participationSection();
  $('#app').replaceWith(el('main', { id: 'contenido-principal' }, [hero, codices, what, ecosystem, projectSection, principleSection, technologySection, impactSection, tlatolliSection, aboutSection, participate]));
}

function participationSection() {
  const profiles = [['Instituciones', 'Gobierno, universidades, centros de investigación y organizaciones.'], ['Creadores y comunidades', 'Artistas, colectivos, espacios culturales y proyectos comunitarios.'], ['Empresas y aliados', 'Colaboración tecnológica, estratégica o de implementación.'], ['Talento', 'Personas interesadas en contribuir desde diseño, tecnología, investigación, comunicación u otras disciplinas.']];
  const channel = getContactChannel(); const form = el('form', { className: 'contact-form' }, [el('div', { className: 'field' }, [el('label', { htmlFor: 'profile', text: 'Quiero participar como' }), el('select', { id: 'profile', name: 'profile' }, profiles.map(([label]) => el('option', { value: label, text: label })))]), el('div', { className: 'field' }, [el('label', { htmlFor: 'name', text: 'Nombre' }), el('input', { id: 'name', name: 'name', type: 'text', autocomplete: 'name', disabled: !channel })]), el('div', { className: 'field' }, [el('label', { htmlFor: 'organization', text: 'Organización (opcional)' }), el('input', { id: 'organization', name: 'organization', type: 'text', disabled: !channel })]), el('div', { className: 'field' }, [el('label', { htmlFor: 'email', text: 'Correo electrónico' }), el('input', { id: 'email', name: 'email', type: 'email', autocomplete: 'email', disabled: !channel })]), el('div', { className: 'field' }, [el('label', { htmlFor: 'message', text: '¿Qué te gustaría conversar?' }), el('textarea', { id: 'message', name: 'message', disabled: !channel })]), el('label', { className: 'check' }, [el('input', { type: 'checkbox', name: 'privacy', disabled: !channel }), el('span', {}, [el('span', { text: 'He leído y acepto el ' }), el('a', { href: routes.privacidad, text: 'Aviso de privacidad' })])]), channel ? el('a', { className: 'button', href: channel, target: '_blank', rel: 'noopener noreferrer', text: 'Iniciar conversación en canal externo' }) : el('button', { className: 'button', type: 'button', disabled: true, text: 'Canal de contacto próximamente' })]);
  if (!channel) form.addEventListener('submit', (event) => { event.preventDefault(); announce('El canal de contacto está pendiente de configuración'); });
  return section('anchor-target', [heading('Participa', 'Hagamos que la tecnología se mueva con propósito.', 'Si representas a una institución, comunidad, empresa o equipo; si creas cultura; o si quieres aportar talento, cuéntanos qué te gustaría construir o explorar con OLLIN.'), el('div', { className: 'participation' }, [el('div', { className: 'profile-list' }, profiles.map(([title, description]) => el('article', { className: 'profile-item' }, [el('h3', { text: title }), el('p', { className: 'muted', text: description })]))), el('div', { className: 'prose' }, [notice(channel ? 'El contacto se abrirá en un servicio externo. Revisa su aviso de privacidad antes de compartir datos.' : 'Esta versión no envía ni almacena información. El formulario es una referencia visual hasta contar con endpoint, protección y aviso legal aprobados.'), form])])], 'participa');
}

function renderProjects() { const input = el('input', { type: 'search', name: 'q', placeholder: 'Buscar proyecto', attrs: { 'aria-label': 'Buscar proyecto' } }); const grid = el('div', { className: 'grid grid-3' }, projects.map(projectCard)); input.addEventListener('input', () => { const query = input.value.toLowerCase().trim(); grid.replaceChildren(...projects.filter((p) => `${p.name} ${p.tagline} ${p.description}`.toLowerCase().includes(query)).map(projectCard)); }); return frame('Proyectos', 'El movimiento toma distintas formas.', 'Cada iniciativa parte de una necesidad concreta y conserva su identidad. Los estados visibles son demostrativos y requieren confirmación.', [section('', [el('div', { className: 'listing-toolbar' }, [input, el('span', { className: 'muted', text: `${projects.length} proyectos de ejemplo` })]), grid])]); }
function renderPrinciples() { return frame('Principios', 'La tecnología también expresa valores.', 'Una guía editorial para orientar decisiones, comunicación y relaciones.', [section('', [el('div', { className: 'grid grid-3' }, principles.map(principleCard)), notice('Estos principios son públicos y conceptuales; no constituyen una certificación ni una garantía absoluta.')])]); }
function renderTechnology() {
  const cards = capabilities.map((item) => el('article', { className: 'tech-card' }, [el('h3', { text: item.title }), el('p', { text: item.description })]));
  const technology = section('dark', [el('div', { className: 'tech-grid' }, cards), notice('Esta descripción es conceptual y no revela arquitectura, algoritmos ni controles internos.')]);
  return frame('Tecnología', 'Infraestructura para conectar sin perder identidad.', 'Capacidades de alto nivel, sin revelar arquitectura, proveedores ni controles internos.', [technology]);
}
function renderImpact() { return frame('Impacto', 'Tecnología que mueve capacidades, no solo pantallas.', 'Objetivos de diseño, no resultados medidos.', [section('', [el('div', { className: 'grid grid-4' }, impact.map(impactCard)), notice('Las métricas se publicarán únicamente cuando existan datos verificables y autorización para comunicarlos.')])]); }
function renderTlatolli() { return frame('Tlatolli', 'Ideas que ponen la tecnología en conversación.', 'Espacio editorial preparado para recibir publicaciones aprobadas.', [section('', [notice('Estamos preparando nuevas publicaciones. Vuelve pronto.'), el('div', { className: 'grid grid-3' }, articles.map(articleCard))])]); }
function renderAbout() { return frame('Sobre OLLIN', 'Ollin significa movimiento.', 'Origen, visión y contexto de una marca matriz para proyectos conectados.', [section('', [el('div', { className: 'prose' }, [el('p', { text: 'El nombre retoma el concepto náhuatl ollin, asociado con el movimiento y la transformación. Para nosotros, ese movimiento conecta personas, información, cultura, conocimiento, oportunidades y comunidades.' }), el('p', { text: 'OLLIN nace de una convicción: México puede construir tecnología con identidad propia, rigor y propósito humano. Proyectos como Cuicoyan convierten esa visión en experiencias concretas y abren el camino para un ecosistema mayor.' }), notice('No buscamos poner una identidad cultural sobre la tecnología. Buscamos que la tecnología nazca del contexto, dialogue con él y contribuya a moverlo.')])])]); }
function renderContact() { const p = participationSection(); const main = frame('Participa', 'Hagamos que la tecnología se mueva con propósito.', 'La vía de conversación está disponible solo cuando existe un canal aprobado.', [p]); return main; }
function renderEcosystem() { return frame('Ecosistema', 'Una base compartida. Muchas experiencias posibles.', 'Diagrama conceptual de relaciones públicas; no representa componentes internos.', [section('', [createEcosystemDiagram(), notice('Vista conceptual: no muestra nodos activos, proveedores, protocolos ni datos de red.')])]); }
function renderPrivacy() { return frame('Información legal', 'Aviso de privacidad.', 'Texto de staging pendiente de validación jurídica.', [section('', [notice('Esta entrega no crea cuentas, no solicita correo y no incorpora analítica. El tema se guarda como preferencia local; los formularios permanecen deshabilitados sin canal aprobado.'), el('div', { className: 'prose' }, [el('p', { text: 'Antes de publicar se debe incorporar el responsable, las finalidades, los derechos aplicables, la versión y un mecanismo de contacto legal aprobado.' }), el('p', { className: 'muted', text: 'Versión de staging · no sustituye asesoría legal.' })])])]); }
function renderParticipationPlaceholder(routeKey) { const labels = { instituciones: ['Instituciones', 'Información para una conversación institucional, sin captura de datos.'], comunidades: ['Creadores y comunidades', 'Una ruta editorial para explorar colaboración cultural y comunitaria.'], talento: ['Talento', 'Un espacio futuro para conocer formas de contribuir al ecosistema.'], propuestas: ['Propuestas de proyectos', 'Una vía futura para compartir una iniciativa, pendiente de canal y criterios públicos.'] }; const [title, desc] = labels[routeKey]; return frame('Participa', title, desc, [section('', [el('div', { className: 'placeholder' }, [el('span', { className: 'demo', text: 'Próximamente' }), el('h2', { text: 'Esta ruta aún no recibe información.' }), el('p', { className: 'muted', text: 'No hay formularios, archivos ni solicitudes almacenadas en esta entrega.' }), el('a', { className: 'button secondary', href: routes.contacto, text: 'Volver a contacto' })])])]); }
function renderNotFound() { return frame('404', 'Esta ruta todavía no existe.', 'Regresa al inicio para conocer el ecosistema.', [section('', [el('a', { className: 'button', href: routes.home, text: 'Volver al inicio' })])]); }

const route = routeForPath(); renderShell(route); switch (route) { case 'home': renderHome(); break; case 'proyectos': renderProjects(); break; case 'principios': renderPrinciples(); break; case 'tecnologia': renderTechnology(); break; case 'impacto': renderImpact(); break; case 'sobre': renderAbout(); break; case 'tlatolli': renderTlatolli(); break; case 'contacto': renderContact(); break; case 'privacidad': renderPrivacy(); break; case 'ecosistema': renderEcosystem(); break; case 'instituciones': case 'comunidades': case 'talento': case 'propuestas': renderParticipationPlaceholder(route); break; default: renderNotFound(); }
renderFooter();
